Website = "https://github.com/heathcliff26/cultures-trainer"

[Details]
Icon = "packages/io.github.heathcliff26.cultures-trainer.png"
Name = "Cultures Trainer"
ID = "io.github.heathcliff26.cultures-trainer"
Version = "${gui_version}"
Build = 0

[Migrations]
fyneDo = true
